import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context/useContext";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer"; 
import StepContext from "@/features/cadastro_projeto/StepContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="min-h-screen flex flex-col">
      
        <AuthProvider>
<<<<<<< HEAD
          <StepContext>
            <Navbar />
            <main className="flex-grow">{children}</main>
            <Footer /> 
          </StepContext>
          
=======

          <Navbar />
            <main className="flex-grow">{children}</main>
          <Footer /> 

>>>>>>> main
        </AuthProvider>
        
      </body>
    </html>
  );
}