import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context/useContext";
import Navbar from "@/components/Navbar";

import Footer from "@/components/Footer"; 


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <AuthProvider>

          <Navbar />
          <main className="flex-grow">{children}</main>
          <Footer /> 

        </AuthProvider>
      </body>
    </html>
  );
}